### ISSUE TITLE
Install newest versions of numpy, scipy, matplotlib

### ISSUE THREAD

**Issue by neggert** [dmwm/cmssh#12]
The versions of these libraries that are installed with CMSSW are somewhat old. Could the cmssh installer pull down the newest versions?

**Comment by neggert** [comment]
Or install pip and give access to it from within cmssh so that the user can easily install packages themselves.

**Comment by vkuznet** [comment]
The point is that I use CMSSW python/gcc versions supplied with given release. So everything comes from CMSSW repository. If I pull newest versions of packages they need to be recompiled with python/gcc version supplied by release. And then if you switch (once I'll add this feature) between your releases you'll need to recompile/re-deploy it again. I need to think about how it should be done.

**Comment by vkuznet** [comment]
Nic, could you please try new cmssh_install.py Now it uses pip to install internals, and I added pip shell command. The soft will be installed correctly into soft/install area. So you can install latest numpy, etc. (I only tried numpy) and pip will correctly pick proper python/gcc (from CMSSW). Once new package is installed you'll need to restart cmssh. I need to think how to reload imports.

**Comment by neggert** [comment]
For reloads, can't you just do `reload(library)`?

pip seems to work properly. numpy installs successfully. I had problems with matplotlib and scipy, but I think it's just having trouble finding includes and libraries. I can probably fix it myself with a bit of mucking around. Those fixes are probably beyond the scope of cmssh, as a user advanced enough to install their own packages should be able to figure out how to get them compiling.

**Comment by vkuznet** [comment]
I want to make reload transparent to users, so I'll play with it a little bit. pip addition seems really useful since you can add whatever you like into your shell without any tweaking to underlying OS. The issues with compilations are tricky, that's why CMS builds entire universe. But I agree I should not concentrate on those issues for time being. My goal now to make usable OSX/Linux environment and allow release switching. Once this is done I can release first version to CMS and then revisit milestones.
