### ISSUE TITLE
cmsenv problem

### ISSUE THREAD

**Issue by heinzK1X** [dmwm/cmssh#49]
I get an error on cmsenv (see below). I guess, it's my crazy machine again.. Haven't tested lxplus on yet. 
cheers, Heiner

cms-sh|3> cmsenv

ERROR: OSError, fail to execute cmd=['eval', '`scramv1', 'runtime', '-sh`'], kwds={}, error=[Errno 2] No such file or directory

**Comment by vkuznet** [comment]
It seems to me that you installed on a node where there is no scramv1 command (part of CMS environment).
Please note that installer does not really tests presence of CMS commands it only accepts the path to afs or similar area.

**Comment by heinzK1X** [comment]
scramv1 is available. In fact, I source /afs/cern.ch/cms/cmsset_default.sh from afs and both cmsenv and scramv1 are available in the normal shell. Anything else I could check? Thanks!

Am 26.02.2013 um 13:43 schrieb Valentin Kuznetsov:

**Comment by vkuznet** [comment]
Hi,
I think I understand what you did. You login to cmssh and run cmsenv, right?

By default cmssh is not bound to any CMS release, therefore cmsenv should be run once one CMSSW release is setup in cmssh. Try to do the following:

# this will list all available releases on given architecture

cmssh> releases

# install one release you want to work with, for example

cmssh> install CMSSW_5_2_4

cmssh> cmsenv

But I just found that on lxplus we have missing RPM database link (see https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/2777.html). So, until this issue is fixed I don't think cms commands will work under cmssh, since it uses underlying RPM/apt repositories to get information about packages. So, feel free to follow the HN thread for resolution on this issue. Once it will be fixed, please try aforementioned steps in cmssh.

Regards,
Valentin.

**Comment by heinzK1X** [comment]
Hello,
I installed on lxplus now. The problem remains the same. The only thing to work here is cmsrel CMSSW_5_3_6. After this the prompt looks like: CMSSW_5_3_6|n>; I assume this means that the cms environment in proper set. cmsenv doesn't work anywhere.

Am 26.02.2013 um 16:48 schrieb Valentin Kuznetsov:

**Comment by vkuznet** [comment]
Hi,
I thought about stand-alone installation of cmssh when I wrote. So on lxplus it is not required and it is sufficient to use just cmsrel <cmssw_release>. It will proper set environment, i.e. it will run internally cmsenv. So please try to use cmsrel with your release.

Meanwhile, I'll add protection to install/cmsenv when user invoke them in non stand-alone environment.
Valentin

I mistakenly gave you wrong

**Comment by vkuznet** [comment]
Hi,
I fixed ambiguity with install/cmsenv commands in multi-user environment when user uses CMSSW from the system itself. You can update your cmssh installation by using --upgrade flag:

# get new version of installer script

curl -O https://raw.github.com/dmwm/cmssh/master/cmssh_install.py

# invoke your cmssh_install.py command with --upgrade flag, e.g.

python26 ./cmssh_install.py -d $PWD --arch=slc5_amd64_gcc462 --cmssw=/afs/cern.ch/cms --multi-user --vers
ion=master --upgrade

# upon upgrade and login into cmssh you'll get the following messages when using install/cmsenv commands

cms-sh|1> install CMSSW_5_0_1

You are not allowed to install new release, since cmssh was installed with system CMSSW install area

cms-sh|2> cmsenv

INFO: Within cmssh it is not required to use cmsenv
please use cmsrel command and CMS release environment will be set for you

I hope it is sufficient and we may close the ticket.
Valentin.

**Comment by vkuznet** [comment]
Closing the ticket.
